# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-30 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField(verbose_name='用户ID')),
                ('uid2', models.IntegerField(verbose_name='用户ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('uid1', 'uid2')]),
        ),
    ]
