# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-25 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性别')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('南京', '南京'), ('苏州', '苏州'), ('深圳', '深圳'), ('无锡', '无锡'), ('香港', '香港'), ('台湾', '台湾'), ('合肥', '合肥')], max_length=20, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=2, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='是否开启震动')),
                ('only_matche', models.BooleanField(default=True, verbose_name='不不让为匹配的人人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自自动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=16, unique=True, verbose_name='手手机号')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(default='1900-01-01', verbose_name='生日')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人人形象')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('南京', '南京'), ('苏州', '苏州'), ('深圳', '深圳'), ('无锡', '无锡'), ('香港', '香港'), ('台湾', '台湾'), ('合肥', '合肥')], max_length=20, verbose_name='常居地')),
            ],
        ),
    ]
