# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-19 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1900-01-01', verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('南京', '南京'), ('苏州', '苏州'), ('深圳', '深圳'), ('无锡', '无锡'), ('香港', '香港'), ('台湾', '台湾'), ('合肥', '合肥')], max_length=20, verbose_name='常居地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phonenum',
            field=models.CharField(max_length=16, unique=True, verbose_name='手手机号'),
        ),
    ]
