# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-29 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='dating_location',
        ),
    ]
